name: news_prediction
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - pytorch=2.2.2
  - safetensors=0.4.2
  - scikit-image=0.22.0
  - scikit-learn=1.2.2
  - scipy=1.12.0
  - scrapy=2.11.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - tokenizers=0.15.1
  - transformers=4.37.2
